import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

const root = new URL('..', import.meta.url)
const file = (path) => fileURLToPath(new URL(path, root))
const text = (path) => readFileSync(file(path), 'utf8')

test('desktop shell contract is represented in the project', () => {
  const cargo = text('src-tauri/Cargo.toml')
  const rust = text('src-tauri/src/lib.rs')
  const process = text('src-tauri/src/process.rs')
  const runtime = text('src-tauri/src/runtime.rs')
  const state = text('src-tauri/src/state.rs')
  const config = text('src-tauri/tauri.conf.json')
  const readme = text('README.md')
  const chineseReadme = text('README.zh-CN.md')

  assert.match(cargo, /tauri-plugin-notification/)
  assert.match(rust, /generate_handler!/)
  assert.match(process, /KILL_ON_JOB_CLOSE/)
  assert.match(process, /127\.0\.0\.1/)
  assert.match(runtime, /@deepseek-ai\/dsh@/)
  assert.match(runtime, /--no-install/)
  assert.match(runtime, /detect_local/)
  assert.match(runtime, /ensure_bundled_node/)
  assert.match(config, /embedBootstrapper/)
  assert.match(config, /runtime-assets\/node/)
  assert.match(config, /"decorations": false/)
  assert.match(config, /icons\/icon\.ico/)
  assert.match(rust, /default_window_icon\(\)/)
  assert.match(rust, /fn minimize_window/)
  assert.match(rust, /fn toggle_maximize/)
  assert.match(rust, /fn hide_window/)
  assert.match(rust, /fn start_window_dragging/)
  assert.match(rust, /fn stop_dsh/)
  assert.match(rust, /web_url/)
  assert.match(rust, /state\.runtime_source = RUNTIME_SOURCE_MANAGED\.to_string\(\)/)
  assert.match(rust, /自动切换到托管运行时/)
  assert.match(text('src-tauri/src/main.rs'), /windows_subsystem = "windows"/)
  assert.match(process, /CREATE_NO_WINDOW/)
  assert.match(runtime, /CREATE_NO_WINDOW/)
  assert.match(state, /window_bounds/)
  assert.match(state, /THEME_SYSTEM/)
  assert.match(config, /frame-src 'self' http:\/\/127\.0\.0\.1:\*/) 
  assert.match(readme, /\[README\.zh-CN\.md\]\(README\.zh-CN\.md\)/)
  assert.match(chineseReadme, /\[README\.md\]\(README\.md\)/)
  assert.doesNotMatch(readme, /choose a workspace/)
  assert.doesNotMatch(chineseReadme, /选择工作区/)
  assert.doesNotMatch(rust, /choose-workspace/)
})

test('bridge plugin is inert without desktop environment variables', () => {
  const host = text('plugins/dsh-desktop-bridge/lib/index.js')
  assert.match(host, /DSH_DESKTOP_CTRL/)
  assert.match(host, /DSH_DESKTOP_TOKEN/)
  assert.match(host, /if \(!CONTROL \|\| !TOKEN\) return/)
  assert.match(host, /turn\/end/)
})

test('plugin market contract is represented in the Rust, UI and fixture layers', () => {
  const rust = text('src-tauri/src/market.rs')
  const mainRust = text('src-tauri/src/lib.rs')
  const html = text('dist/index.html')
  const javascript = text('dist/app.js')
  const fixture = JSON.parse(text('plugins/dsh-market-example/package.json'))

  assert.match(mainRust, /search_market_plugins/)
  assert.match(mainRust, /install_market_plugin/)
  assert.match(mainRust, /uninstall_market_plugin/)
  assert.match(rust, /@p-dsh-market\//)
  assert.match(rust, /dsh\.client\.platform/)
  assert.match(rust, /dsh\.bundle\.patch/)
  assert.match(rust, /dsh\.market\.capabilities/)
  assert.match(rust, /--search-limit/)
  assert.match(rust, /pnpm\.cmd/)
  assert.match(rust, /DSH_HOME/)
  assert.match(html, /titlebar-market/)
  assert.match(html, /id="market-view"/)
  assert.match(html, /market-search-form/)
  assert.match(javascript, /viewMode = 'market'/)
  assert.match(javascript, /search_market_plugins/)
  assert.match(javascript, /install_market_plugin/)
  assert.match(javascript, /uninstall_market_plugin/)
  assert.equal(fixture.name, '@p-dsh-market/example')
  assert.equal(fixture.exports['./client'], './lib/client.js')
  assert.equal(fixture.dsh.client.platform, 'web')
  assert.equal(fixture.dsh.bundle.patch, './cordis.patch.yml')
  assert.deepEqual(fixture.dsh.market.capabilities.sort(), ['client', 'host', 'skills'])
})

test('splash page exposes recovery actions', () => {
  const html = text('dist/index.html')
  const javascript = text('dist/app.js')
  assert.match(html, />启动</)
  assert.match(html, />进入页面</)
  assert.match(html, />重启</)
  assert.match(html, /回滚|安装并切换/)
  assert.match(html, /打开日志目录/)
  assert.match(html, /window-minimize/)
  assert.match(html, /window-maximize/)
  assert.match(html, /window-close/)
  assert.match(html, /titlebar-drag/)
  assert.match(html, /titlebar-home/)
  assert.match(html, /class="brand-mark">D<\/div>/)
  assert.match(html, /class="titlebar-dot">D<\/span>/)
  assert.match(html, /dsh-frame/)
  assert.match(html, /app-home/)
  assert.match(html, /app-update/)
  assert.match(html, /app-upgrade/)
  assert.match(html, /app-stop/)
  assert.match(html, /toggle-dsh/)
  assert.match(html, /enter-dsh/)
  assert.match(html, /data-theme-choice="light"/)
  assert.match(html, /data-theme-choice="dark"/)
  assert.match(html, /data-theme-choice="system"/)
  assert.doesNotMatch(html, /选择文件夹/)
  assert.match(html, /运行来源/)
  assert.match(html, /use-local/)
  assert.match(html, /use-managed/)
  assert.match(javascript, /versionsOf/)
  assert.match(javascript, /toggle_maximize/)
  assert.match(javascript, /start_window_dragging/)
  assert.match(javascript, /stop_dsh/)
  assert.match(javascript, /webUrl/)
  assert.match(javascript, /loadedFrameUrl/)
  assert.match(javascript, /function enterDsh/)
  assert.match(javascript, /function toggleDsh/)
  assert.match(javascript, /function closeWindow/)
  assert.match(javascript, /set_runtime_source/)
  assert.match(javascript, /set_theme/)
  assert.match(javascript, /prefers-color-scheme: dark/)
  assert.match(javascript, /detect_local_runtime/)
  assert.equal(existsSync(file('runtime-assets/node/README.md')), true)
})

test('javascript artifacts pass node syntax validation', () => {
  for (const path of [
    'dist/app.js',
    'plugins/dsh-desktop-bridge/lib/index.js',
    'plugins/dsh-desktop-bridge/lib/client.js',
    'plugins/dsh-market-example/lib/index.js',
    'plugins/dsh-market-example/lib/client.js',
  ]) {
    execFileSync(process.execPath, ['--check', file(path)], { stdio: 'pipe' })
  }
})
